### ISSUE TITLE
Misleading error message for SSL certificate expiration

### ISSUE THREAD

**Issue by cmaster11** [skx/overseer#49]
Not necessarily an issue, because I think it's really an edge case, but reporting for the sake of knowledge.

---

On May 30th a root CA SSL cert will expire and will be replaced by a new one, valid through 2038, which is already available.

https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

The curious case here is, I've been running Overseer on a quite old Docker build, ~180d, which probably did not already include the new CA certs. So, because of this situation, Overseer started throwing SSL cert expiring for my domain (24 days left), while in reality it was the CA one (11 days) that was marked for expiry.

So the issue is just that Overseer was not reporting that the expiring SSL cert was the CA one and not the mydomain.com.

This is absolutely and edge case, but relevant in long-running systems (especially docker, where you have to rebuild an image to update SSL certs).

The logs were:

```
SSLExpiration - certificate: *.mydomain.com expires in 596 hours (24 days)
SSLExpiration - certificate: Sectigo RSA Domain Validation Secure Server CA expires in 93092 hours (3878 days)
SSLExpiration - certificate: USERTrust RSA Certification Authority expires in 154892 hours (6453 days)
SSLExpiration - certificate: *.mydomain.com expires in 596 hours (24 days)
SSLExpiration - certificate: Sectigo RSA Domain Validation Secure Server CA expires in 93092 hours (3878 days)
SSLExpiration - certificate: USERTrust RSA CertifiAddTrust External CA Rootcation Authority expires in 271 hours (11 days)
SSLExpiration - certificate:  expires in 271 hours (11 days)
```

The reported error was:

```
Error: SSL certificate will expire in 287 hours (11 days)
```

**Comment by skx** [comment]
I can see how this would cause surprises, for sure!

The error message should probably refer to common-name of the certificate involved.
